import maya.cmds as cmds
def start():
	funMainMenu = cmds.menu(label = 'fun.zheng', tearOff = True, parent = 'MayaWindow')
	cmds.menuItem(label = 'modeling', subMenu = True)
	cmds.menuItem(label = 'Checking Box', command = 'import modeling.checkModel as cm; reload(cm); cm.checkModel()')
	cmds.menuItem(label = 'UV Smart Project', command = 'import modeling.uvCalcSmartProject as uvsmart; reload(uvsmart); uvsmart.main()')
	cmds.setParent(funMainMenu, menu = True)
	cmds.menuItem(label = 'animation', subMenu = True)
	cmds.menuItem(label = 'animation panel', command = 'import animation.StartSYH_anim as s_anim; reload(s_anim); s_anim.main()')
	cmds.setParent(funMainMenu, menu = True)
	cmds.menuItem(label = 'rigging', subMenu = True)
	cmds.menuItem(label = 'SuperFace', command = 'import rigging.superFace as sf; reload(sf); sf.main()')
	cmds.setParent(funMainMenu, menu = True)
	cmds.menuItem(label = 'three.js', subMenu = True)
	cmds.menuItem(label = 'import and export mesh', command = 'import threejs.importAndExport.meshFileManager as immesh; reload(immesh); immesh.main()')
	cmds.menuItem(label = 'import and export geo', command = 'import threejs.importAndExport.geoFileManager as imgeo; reload(imgeo); imgeo.main()')
	cmds.menuItem(label = 'import and export project datas', command = 'import threejs.importAndExport.importAndExport as imEx; reload(imEx); imEx.main()')
	cmds.menuItem(label = 'JXZY Batch', command = 'import threejs.importAndExport.jxzyBatch as imjxzyb; reload(imjxzyb); imjxzyb.main()')
	cmds.menuItem(label = 'import and export world', command = 'import threejs.importAndExport.worldFileManager as imworld; reload(imworld); imworld.main()')
	cmds.setParent(funMainMenu, menu = True)
	cmds.menuItem(label = 'misc', subMenu = True)
	cmds.menuItem(label = 'import and export stl', command = 'import misc.stlFileManager as imstl; reload(imstl); imstl.main()')
	cmds.menuItem(label = 'generate cubemap', command = 'import misc.renderCubemap as renCm; reload(renCm); renCm.main()')
	cmds.menuItem(label = 'calculator volume', command = 'import misc.volumeCalculator as vc; reload(vc); vc.main()')
if __name__ == '__main__':
	start();
