# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SYH_anim_panel_fin.ui'
#
# Created: Mon Jan 09 20:18:01 2012
#      by: PySide UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(486, 459)
        Form.setMinimumSize(QtCore.QSize(136, 74))
        Form.setMaximumSize(QtCore.QSize(486, 459))
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "SYH_RigPanel", None, QtGui.QApplication.UnicodeUTF8))
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(9, 9, 471, 39))
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(508, 39))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.comboBox = QtGui.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(9, 9, 451, 21))
        self.comboBox.setMinimumSize(QtCore.QSize(451, 21))
        self.comboBox.setMaximumSize(QtCore.QSize(451, 21))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(9, 54, 471, 399))
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(508, 399))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.ATD_head = QtGui.QPushButton(self.tab)
        self.ATD_head.setGeometry(QtCore.QRect(200, 10, 61, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ATD_head.sizePolicy().hasHeightForWidth())
        self.ATD_head.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_head.setPalette(palette)
        self.ATD_head.setText(_fromUtf8(""))
        self.ATD_head.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_head.setObjectName(_fromUtf8("ATD_head"))
        self.ATD_R_shoulder = QtGui.QPushButton(self.tab)
        self.ATD_R_shoulder.setGeometry(QtCore.QRect(140, 70, 44, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_shoulder.setPalette(palette)
        self.ATD_R_shoulder.setText(_fromUtf8(""))
        self.ATD_R_shoulder.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_shoulder.setObjectName(_fromUtf8("ATD_R_shoulder"))
        self.ATD_R_arm_sec01 = QtGui.QPushButton(self.tab)
        self.ATD_R_arm_sec01.setGeometry(QtCore.QRect(120, 100, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_arm_sec01.setPalette(palette)
        self.ATD_R_arm_sec01.setText(_fromUtf8(""))
        self.ATD_R_arm_sec01.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_arm_sec01.setObjectName(_fromUtf8("ATD_R_arm_sec01"))
        self.ATD_R_arm_pole = QtGui.QPushButton(self.tab)
        self.ATD_R_arm_pole.setGeometry(QtCore.QRect(50, 70, 41, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_arm_pole.setPalette(palette)
        self.ATD_R_arm_pole.setText(_fromUtf8(""))
        self.ATD_R_arm_pole.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_arm_pole.setObjectName(_fromUtf8("ATD_R_arm_pole"))
        self.ATD_R_twist = QtGui.QPushButton(self.tab)
        self.ATD_R_twist.setGeometry(QtCore.QRect(50, 140, 81, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_twist.setPalette(palette)
        self.ATD_R_twist.setText(_fromUtf8(""))
        self.ATD_R_twist.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_twist.setObjectName(_fromUtf8("ATD_R_twist"))
        self.ATD_R_allfiger = QtGui.QPushButton(self.tab)
        self.ATD_R_allfiger.setGeometry(QtCore.QRect(50, 180, 81, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_allfiger.setPalette(palette)
        self.ATD_R_allfiger.setText(_fromUtf8(""))
        self.ATD_R_allfiger.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_allfiger.setObjectName(_fromUtf8("ATD_R_allfiger"))
        self.ATD_root = QtGui.QPushButton(self.tab)
        self.ATD_root.setGeometry(QtCore.QRect(170, 210, 121, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_root.setPalette(palette)
        self.ATD_root.setText(_fromUtf8(""))
        self.ATD_root.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_root.setObjectName(_fromUtf8("ATD_root"))
        self.ATD_R_ff_01 = QtGui.QPushButton(self.tab)
        self.ATD_R_ff_01.setGeometry(QtCore.QRect(110, 200, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_ff_01.setPalette(palette)
        self.ATD_R_ff_01.setText(_fromUtf8(""))
        self.ATD_R_ff_01.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_ff_01.setObjectName(_fromUtf8("ATD_R_ff_01"))
        self.ATD_R_fr_01 = QtGui.QPushButton(self.tab)
        self.ATD_R_fr_01.setGeometry(QtCore.QRect(70, 200, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_fr_01.setPalette(palette)
        self.ATD_R_fr_01.setText(_fromUtf8(""))
        self.ATD_R_fr_01.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_fr_01.setObjectName(_fromUtf8("ATD_R_fr_01"))
        self.ATD_R_fl_01 = QtGui.QPushButton(self.tab)
        self.ATD_R_fl_01.setGeometry(QtCore.QRect(50, 200, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_fl_01.setPalette(palette)
        self.ATD_R_fl_01.setText(_fromUtf8(""))
        self.ATD_R_fl_01.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_fl_01.setObjectName(_fromUtf8("ATD_R_fl_01"))
        self.ATD_R_fm_01 = QtGui.QPushButton(self.tab)
        self.ATD_R_fm_01.setGeometry(QtCore.QRect(90, 200, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_fm_01.setPalette(palette)
        self.ATD_R_fm_01.setText(_fromUtf8(""))
        self.ATD_R_fm_01.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_fm_01.setObjectName(_fromUtf8("ATD_R_fm_01"))
        self.ATD_R_fr_02 = QtGui.QPushButton(self.tab)
        self.ATD_R_fr_02.setGeometry(QtCore.QRect(70, 220, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_fr_02.setPalette(palette)
        self.ATD_R_fr_02.setText(_fromUtf8(""))
        self.ATD_R_fr_02.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_fr_02.setObjectName(_fromUtf8("ATD_R_fr_02"))
        self.ATD_R_fl_02 = QtGui.QPushButton(self.tab)
        self.ATD_R_fl_02.setGeometry(QtCore.QRect(50, 220, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_fl_02.setPalette(palette)
        self.ATD_R_fl_02.setText(_fromUtf8(""))
        self.ATD_R_fl_02.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_fl_02.setObjectName(_fromUtf8("ATD_R_fl_02"))
        self.ATD_R_fm_02 = QtGui.QPushButton(self.tab)
        self.ATD_R_fm_02.setGeometry(QtCore.QRect(90, 220, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_fm_02.setPalette(palette)
        self.ATD_R_fm_02.setText(_fromUtf8(""))
        self.ATD_R_fm_02.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_fm_02.setObjectName(_fromUtf8("ATD_R_fm_02"))
        self.ATD_R_ff_03 = QtGui.QPushButton(self.tab)
        self.ATD_R_ff_03.setGeometry(QtCore.QRect(110, 240, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_ff_03.setPalette(palette)
        self.ATD_R_ff_03.setText(_fromUtf8(""))
        self.ATD_R_ff_03.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_ff_03.setObjectName(_fromUtf8("ATD_R_ff_03"))
        self.ATD_R_fr_03 = QtGui.QPushButton(self.tab)
        self.ATD_R_fr_03.setGeometry(QtCore.QRect(70, 240, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_fr_03.setPalette(palette)
        self.ATD_R_fr_03.setText(_fromUtf8(""))
        self.ATD_R_fr_03.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_fr_03.setObjectName(_fromUtf8("ATD_R_fr_03"))
        self.ATD_R_fl_03 = QtGui.QPushButton(self.tab)
        self.ATD_R_fl_03.setGeometry(QtCore.QRect(50, 240, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_fl_03.setPalette(palette)
        self.ATD_R_fl_03.setText(_fromUtf8(""))
        self.ATD_R_fl_03.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_fl_03.setObjectName(_fromUtf8("ATD_R_fl_03"))
        self.ATD_R_fm_03 = QtGui.QPushButton(self.tab)
        self.ATD_R_fm_03.setGeometry(QtCore.QRect(90, 240, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_fm_03.setPalette(palette)
        self.ATD_R_fm_03.setText(_fromUtf8(""))
        self.ATD_R_fm_03.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_fm_03.setObjectName(_fromUtf8("ATD_R_fm_03"))
        self.ATD_R_leg_sec = QtGui.QPushButton(self.tab)
        self.ATD_R_leg_sec.setGeometry(QtCore.QRect(170, 270, 21, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_leg_sec.setPalette(palette)
        self.ATD_R_leg_sec.setText(_fromUtf8(""))
        self.ATD_R_leg_sec.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_leg_sec.setObjectName(_fromUtf8("ATD_R_leg_sec"))
        self.ATD_L_leg_sec = QtGui.QPushButton(self.tab)
        self.ATD_L_leg_sec.setGeometry(QtCore.QRect(270, 270, 21, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_leg_sec.setPalette(palette)
        self.ATD_L_leg_sec.setText(_fromUtf8(""))
        self.ATD_L_leg_sec.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_leg_sec.setObjectName(_fromUtf8("ATD_L_leg_sec"))
        self.ATD_R_leg = QtGui.QPushButton(self.tab)
        self.ATD_R_leg.setGeometry(QtCore.QRect(120, 310, 71, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_leg.setPalette(palette)
        self.ATD_R_leg.setText(_fromUtf8(""))
        self.ATD_R_leg.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_leg.setObjectName(_fromUtf8("ATD_R_leg"))
        self.ATD_L_leg = QtGui.QPushButton(self.tab)
        self.ATD_L_leg.setGeometry(QtCore.QRect(270, 310, 69, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_leg.setPalette(palette)
        self.ATD_L_leg.setText(_fromUtf8(""))
        self.ATD_L_leg.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_leg.setObjectName(_fromUtf8("ATD_L_leg"))
        self.ATD_R_leg_pole = QtGui.QPushButton(self.tab)
        self.ATD_R_leg_pole.setGeometry(QtCore.QRect(50, 270, 41, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_leg_pole.setPalette(palette)
        self.ATD_R_leg_pole.setText(_fromUtf8(""))
        self.ATD_R_leg_pole.setObjectName(_fromUtf8("ATD_R_leg_pole"))
        self.ATD_L_leg_pole = QtGui.QPushButton(self.tab)
        self.ATD_L_leg_pole.setGeometry(QtCore.QRect(370, 270, 41, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_leg_pole.setPalette(palette)
        self.ATD_L_leg_pole.setText(_fromUtf8(""))
        self.ATD_L_leg_pole.setObjectName(_fromUtf8("ATD_L_leg_pole"))
        self.ATD_selectall = QtGui.QPushButton(self.tab)
        self.ATD_selectall.setGeometry(QtCore.QRect(350, 340, 41, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_selectall.setPalette(palette)
        self.ATD_selectall.setText(_fromUtf8(""))
        self.ATD_selectall.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_selectall.setObjectName(_fromUtf8("ATD_selectall"))
        self.ATD_R_ff_02 = QtGui.QPushButton(self.tab)
        self.ATD_R_ff_02.setGeometry(QtCore.QRect(110, 220, 21, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_ff_02.setPalette(palette)
        self.ATD_R_ff_02.setText(_fromUtf8(""))
        self.ATD_R_ff_02.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_ff_02.setObjectName(_fromUtf8("ATD_R_ff_02"))
        self.ATD_R_figer_sec = QtGui.QPushButton(self.tab)
        self.ATD_R_figer_sec.setGeometry(QtCore.QRect(30, 200, 21, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_figer_sec.setPalette(palette)
        self.ATD_R_figer_sec.setText(_fromUtf8(""))
        self.ATD_R_figer_sec.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_figer_sec.setObjectName(_fromUtf8("ATD_R_figer_sec"))
        self.ATD_L_fm_03 = QtGui.QPushButton(self.tab)
        self.ATD_L_fm_03.setGeometry(QtCore.QRect(350, 240, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_fm_03.setPalette(palette)
        self.ATD_L_fm_03.setText(_fromUtf8(""))
        self.ATD_L_fm_03.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_fm_03.setObjectName(_fromUtf8("ATD_L_fm_03"))
        self.ATD_L_fl_03 = QtGui.QPushButton(self.tab)
        self.ATD_L_fl_03.setGeometry(QtCore.QRect(390, 240, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_fl_03.setPalette(palette)
        self.ATD_L_fl_03.setText(_fromUtf8(""))
        self.ATD_L_fl_03.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_fl_03.setObjectName(_fromUtf8("ATD_L_fl_03"))
        self.ATD_L_fl_01 = QtGui.QPushButton(self.tab)
        self.ATD_L_fl_01.setGeometry(QtCore.QRect(390, 200, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_fl_01.setPalette(palette)
        self.ATD_L_fl_01.setText(_fromUtf8(""))
        self.ATD_L_fl_01.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_fl_01.setObjectName(_fromUtf8("ATD_L_fl_01"))
        self.ATD_L_fr_03 = QtGui.QPushButton(self.tab)
        self.ATD_L_fr_03.setGeometry(QtCore.QRect(370, 240, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_fr_03.setPalette(palette)
        self.ATD_L_fr_03.setText(_fromUtf8(""))
        self.ATD_L_fr_03.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_fr_03.setObjectName(_fromUtf8("ATD_L_fr_03"))
        self.ATD_L_fm_02 = QtGui.QPushButton(self.tab)
        self.ATD_L_fm_02.setGeometry(QtCore.QRect(350, 220, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_fm_02.setPalette(palette)
        self.ATD_L_fm_02.setText(_fromUtf8(""))
        self.ATD_L_fm_02.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_fm_02.setObjectName(_fromUtf8("ATD_L_fm_02"))
        self.ATD_L_allfiger = QtGui.QPushButton(self.tab)
        self.ATD_L_allfiger.setGeometry(QtCore.QRect(330, 180, 81, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_allfiger.setPalette(palette)
        self.ATD_L_allfiger.setText(_fromUtf8(""))
        self.ATD_L_allfiger.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_allfiger.setObjectName(_fromUtf8("ATD_L_allfiger"))
        self.ATD_L_ff_02 = QtGui.QPushButton(self.tab)
        self.ATD_L_ff_02.setGeometry(QtCore.QRect(330, 220, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_ff_02.setPalette(palette)
        self.ATD_L_ff_02.setText(_fromUtf8(""))
        self.ATD_L_ff_02.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_ff_02.setObjectName(_fromUtf8("ATD_L_ff_02"))
        self.ATD_L_ff_03 = QtGui.QPushButton(self.tab)
        self.ATD_L_ff_03.setGeometry(QtCore.QRect(330, 240, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_ff_03.setPalette(palette)
        self.ATD_L_ff_03.setText(_fromUtf8(""))
        self.ATD_L_ff_03.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_ff_03.setObjectName(_fromUtf8("ATD_L_ff_03"))
        self.ATD_L_fm_01 = QtGui.QPushButton(self.tab)
        self.ATD_L_fm_01.setGeometry(QtCore.QRect(350, 200, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_fm_01.setPalette(palette)
        self.ATD_L_fm_01.setText(_fromUtf8(""))
        self.ATD_L_fm_01.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_fm_01.setObjectName(_fromUtf8("ATD_L_fm_01"))
        self.ATD_L_ff_01 = QtGui.QPushButton(self.tab)
        self.ATD_L_ff_01.setGeometry(QtCore.QRect(330, 200, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_ff_01.setPalette(palette)
        self.ATD_L_ff_01.setText(_fromUtf8(""))
        self.ATD_L_ff_01.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_ff_01.setObjectName(_fromUtf8("ATD_L_ff_01"))
        self.ATD_L_fr_02 = QtGui.QPushButton(self.tab)
        self.ATD_L_fr_02.setGeometry(QtCore.QRect(370, 220, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_fr_02.setPalette(palette)
        self.ATD_L_fr_02.setText(_fromUtf8(""))
        self.ATD_L_fr_02.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_fr_02.setObjectName(_fromUtf8("ATD_L_fr_02"))
        self.ATD_L_fr_01 = QtGui.QPushButton(self.tab)
        self.ATD_L_fr_01.setGeometry(QtCore.QRect(370, 200, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_fr_01.setPalette(palette)
        self.ATD_L_fr_01.setText(_fromUtf8(""))
        self.ATD_L_fr_01.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_fr_01.setObjectName(_fromUtf8("ATD_L_fr_01"))
        self.ATD_L_fl_02 = QtGui.QPushButton(self.tab)
        self.ATD_L_fl_02.setGeometry(QtCore.QRect(390, 220, 21, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_fl_02.setPalette(palette)
        self.ATD_L_fl_02.setText(_fromUtf8(""))
        self.ATD_L_fl_02.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_fl_02.setObjectName(_fromUtf8("ATD_L_fl_02"))
        self.ATD_R_fb_02 = QtGui.QPushButton(self.tab)
        self.ATD_R_fb_02.setGeometry(QtCore.QRect(150, 180, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_fb_02.setPalette(palette)
        self.ATD_R_fb_02.setText(_fromUtf8(""))
        self.ATD_R_fb_02.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_fb_02.setObjectName(_fromUtf8("ATD_R_fb_02"))
        self.ATD_R_fb_03 = QtGui.QPushButton(self.tab)
        self.ATD_R_fb_03.setGeometry(QtCore.QRect(170, 180, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_fb_03.setPalette(palette)
        self.ATD_R_fb_03.setText(_fromUtf8(""))
        self.ATD_R_fb_03.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_fb_03.setObjectName(_fromUtf8("ATD_R_fb_03"))
        self.ATD_R_fb_01 = QtGui.QPushButton(self.tab)
        self.ATD_R_fb_01.setGeometry(QtCore.QRect(130, 180, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_fb_01.setPalette(palette)
        self.ATD_R_fb_01.setText(_fromUtf8(""))
        self.ATD_R_fb_01.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_fb_01.setObjectName(_fromUtf8("ATD_R_fb_01"))
        self.ATD_L_fb_02 = QtGui.QPushButton(self.tab)
        self.ATD_L_fb_02.setGeometry(QtCore.QRect(290, 180, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_fb_02.setPalette(palette)
        self.ATD_L_fb_02.setText(_fromUtf8(""))
        self.ATD_L_fb_02.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_fb_02.setObjectName(_fromUtf8("ATD_L_fb_02"))
        self.ATD_L_fb_01 = QtGui.QPushButton(self.tab)
        self.ATD_L_fb_01.setGeometry(QtCore.QRect(310, 180, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_fb_01.setPalette(palette)
        self.ATD_L_fb_01.setText(_fromUtf8(""))
        self.ATD_L_fb_01.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_fb_01.setObjectName(_fromUtf8("ATD_L_fb_01"))
        self.ATD_L_fb_03 = QtGui.QPushButton(self.tab)
        self.ATD_L_fb_03.setGeometry(QtCore.QRect(270, 180, 20, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_fb_03.setPalette(palette)
        self.ATD_L_fb_03.setText(_fromUtf8(""))
        self.ATD_L_fb_03.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_fb_03.setObjectName(_fromUtf8("ATD_L_fb_03"))
        self.ATD_spline = QtGui.QPushButton(self.tab)
        self.ATD_spline.setGeometry(QtCore.QRect(190, 100, 81, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_spline.setPalette(palette)
        self.ATD_spline.setText(_fromUtf8(""))
        self.ATD_spline.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_spline.setObjectName(_fromUtf8("ATD_spline"))
        self.ATD_L_arm_pole = QtGui.QPushButton(self.tab)
        self.ATD_L_arm_pole.setGeometry(QtCore.QRect(370, 70, 44, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_arm_pole.setPalette(palette)
        self.ATD_L_arm_pole.setText(_fromUtf8(""))
        self.ATD_L_arm_pole.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_arm_pole.setObjectName(_fromUtf8("ATD_L_arm_pole"))
        self.ATD_L_shoulder = QtGui.QPushButton(self.tab)
        self.ATD_L_shoulder.setGeometry(QtCore.QRect(280, 70, 41, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_shoulder.setPalette(palette)
        self.ATD_L_shoulder.setText(_fromUtf8(""))
        self.ATD_L_shoulder.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_shoulder.setObjectName(_fromUtf8("ATD_L_shoulder"))
        self.ATD_L_arm_sec01 = QtGui.QPushButton(self.tab)
        self.ATD_L_arm_sec01.setGeometry(QtCore.QRect(320, 100, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_arm_sec01.setPalette(palette)
        self.ATD_L_arm_sec01.setText(_fromUtf8(""))
        self.ATD_L_arm_sec01.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_arm_sec01.setObjectName(_fromUtf8("ATD_L_arm_sec01"))
        self.ATD_L_twist = QtGui.QPushButton(self.tab)
        self.ATD_L_twist.setGeometry(QtCore.QRect(330, 140, 81, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_twist.setPalette(palette)
        self.ATD_L_twist.setText(_fromUtf8(""))
        self.ATD_L_twist.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_twist.setObjectName(_fromUtf8("ATD_L_twist"))
        self.ATD_L_figer_sec = QtGui.QPushButton(self.tab)
        self.ATD_L_figer_sec.setGeometry(QtCore.QRect(410, 200, 21, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_figer_sec.setPalette(palette)
        self.ATD_L_figer_sec.setText(_fromUtf8(""))
        self.ATD_L_figer_sec.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_figer_sec.setObjectName(_fromUtf8("ATD_L_figer_sec"))
        self.ATD_R_fkik = QtGui.QPushButton(self.tab)
        self.ATD_R_fkik.setGeometry(QtCore.QRect(50, 40, 21, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_fkik.setPalette(palette)
        self.ATD_R_fkik.setText(_fromUtf8(""))
        self.ATD_R_fkik.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_fkik.setObjectName(_fromUtf8("ATD_R_fkik"))
        self.ATD_L_fkik = QtGui.QPushButton(self.tab)
        self.ATD_L_fkik.setGeometry(QtCore.QRect(394, 40, 21, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_fkik.setPalette(palette)
        self.ATD_L_fkik.setText(_fromUtf8(""))
        self.ATD_L_fkik.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_fkik.setObjectName(_fromUtf8("ATD_L_fkik"))
        self.ATD_R_arm_sec02 = QtGui.QPushButton(self.tab)
        self.ATD_R_arm_sec02.setGeometry(QtCore.QRect(110, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_R_arm_sec02.setPalette(palette)
        self.ATD_R_arm_sec02.setText(_fromUtf8(""))
        self.ATD_R_arm_sec02.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_R_arm_sec02.setObjectName(_fromUtf8("ATD_R_arm_sec02"))
        self.ATD_L_arm_sec02 = QtGui.QPushButton(self.tab)
        self.ATD_L_arm_sec02.setGeometry(QtCore.QRect(330, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_L_arm_sec02.setPalette(palette)
        self.ATD_L_arm_sec02.setText(_fromUtf8(""))
        self.ATD_L_arm_sec02.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_L_arm_sec02.setObjectName(_fromUtf8("ATD_L_arm_sec02"))
        self.ATD_bigcircle01 = QtGui.QPushButton(self.tab)
        self.ATD_bigcircle01.setGeometry(QtCore.QRect(170, 340, 121, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_bigcircle01.setPalette(palette)
        self.ATD_bigcircle01.setText(_fromUtf8(""))
        self.ATD_bigcircle01.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_bigcircle01.setObjectName(_fromUtf8("ATD_bigcircle01"))
        self.ATD_bigcircle02 = QtGui.QPushButton(self.tab)
        self.ATD_bigcircle02.setGeometry(QtCore.QRect(170, 360, 121, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_bigcircle02.setPalette(palette)
        self.ATD_bigcircle02.setText(_fromUtf8(""))
        self.ATD_bigcircle02.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_bigcircle02.setObjectName(_fromUtf8("ATD_bigcircle02"))
        self.ATD_flyctrl = QtGui.QPushButton(self.tab)
        self.ATD_flyctrl.setGeometry(QtCore.QRect(70, 340, 41, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ATD_flyctrl.setPalette(palette)
        self.ATD_flyctrl.setText(_fromUtf8(""))
        self.ATD_flyctrl.setProperty("+command", QtGui.QApplication.translate("Form", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ATD_flyctrl.setObjectName(_fromUtf8("ATD_flyctrl"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "ATD", None, QtGui.QApplication.UnicodeUTF8))

